"use client"
import React, { useEffect } from "react";
import "./globals.css";
import Lenis from "lenis";
import { ReactLenis, useLenis } from "lenis/react";
import Navbar from "@/components/navbar/page";
import styles from './global.module.scss';

//export const metadata = {
 // title: "Create Next App",
 // description: "Generated by create next app",
//};

export default function RootLayout({ children }) {
  useEffect(() => {
    const lenis = new Lenis({
      smoothWheel: true,
      smoothTouch: true,
      lerp: 0.5, // Smoothness of the scroll, tweak as needed
    });

    function animate(time) {
      lenis.raf(time);
      requestAnimationFrame(animate);
    }

    requestAnimationFrame(animate);

    return () => lenis.destroy();
  }, []);

  return (
    <html lang="en">
      <body className="antialiased">
        <ReactLenis>
          <Navbar />
          {children}
          </ReactLenis>
      </body>
    </html>
  );
}
